# Generated by Django 5.2.4 on 2025-07-18 11:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Mickey_SSN_DOB_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Mickey_SSN_DOB_New_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Mickey_DL_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_SSN_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_SSN_DOB_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_DLV2_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_Advanced_Lookup_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_DOB_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_Phone_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_Reverse_Phone_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sam_Reverse_SSN_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sergio_SSN_DOB_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Sergio_DL_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                (
                    "Alex_SSN_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99999999"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
